apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
<<<<<<< HEAD
        image: kiran63/ultimate-cicd:replaceImageTag
=======
        image: abhishekf5/ultimate-cicd:13
>>>>>>> c648b317871c859a7fd957ca274470f133fa8376
        ports:
        - containerPort: 8080
